global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chaoscore-api'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
    honor_labels: true

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090'] 