version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chaoschain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Hardhat node with fork at fixed block
  hardhat:
    build:
      context: ..
      dockerfile: scripts/docker/Dockerfile.hardhat
    environment:
      - FORK_BLOCK=5524380
      - FORK_URL=https://eth-sepolia.g.alchemy.com/v2/demo
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI server
  api:
    build:
      context: ..
      dockerfile: scripts/docker/Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chaoschain
      - API_KEYS=demo_key,test_key
      - ETHEREUM_RPC_URL=http://hardhat:8545
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      hardhat:
        condition: service_healthy
    volumes:
      - ../:/app

volumes:
  postgres_data: 