version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chaoschain
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - chaoschain-network

  # Hardhat node with fork at fixed block
  hardhat:
    build:
      context: ..
      dockerfile: scripts/docker/Dockerfile.hardhat
    volumes:
      - ../:/app
    ports:
      - "8545:8545"
    command: npx hardhat node
    networks:
      - chaoschain-network

  # FastAPI server
  api:
    build:
      context: ..
      dockerfile: scripts/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chaoschain
      - API_KEYS=demo_key,test_key
      - ETHEREUM_RPC_URL=http://hardhat:8545
      - LOG_LEVEL=INFO
      - ENABLE_STREAM=1
    depends_on:
      postgres:
        condition: service_healthy
      hardhat:
        condition: service_healthy
    volumes:
      - ../:/app
    command: uvicorn api.rest.app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - chaoschain-network

  frontend:
    image: nginx:alpine
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - chaoschain-network

networks:
  chaoschain-network:
    driver: bridge

volumes:
  postgres_data: 