name: ChaosCore CI

on:
  push:
    paths:
      - 'chaoscore/**'
      - '.github/workflows/chaoscore-ci.yml'
  pull_request:
    paths:
      - 'chaoscore/**'
      - '.github/workflows/chaoscore-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd chaoscore
          pip install -e ".[dev]"
      
      - name: Run linting
        run: |
          cd chaoscore
          black --check .
          isort --check .
          mypy chaoscore/
      
      - name: Run tests
        run: |
          cd chaoscore
          pytest tests/ -v 