name: ChaosChain CI

on:
  push:
    branches: [ main, governance-adaptation ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        run: pytest -q tests/
      - name: Run linting
        run: |
          black --check .
          isort --check .
          mypy agent/

  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run tests
        run: npm test
      - name: Run linting
        run: npm run lint

  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build without SGX feature
        run: cargo build --verbose
      - name: Run tests without SGX feature
        run: cargo test --verbose
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Lint with clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chaoschain_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/chaoschain_test
  
  governance-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: |
          pytest tests/unit/agent/test_governance_agents_adapted.py -v
      
      - name: Run integration tests
        run: |
          pytest tests/integration/test_secure_simulation_poa.py -v
      
      - name: Run demo script
        run: |
          python demo_governance_flow.py --output governance_flow_result.json
      
      - name: Upload demo result
        uses: actions/upload-artifact@v4
        with:
          name: governance-flow-result
          path: governance_flow_result.json
  
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      
      - name: Build frontend
        run: npm run build --prefix frontend
      
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist 