name: ChaosChain CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        run: pytest -q tests/
      - name: Run linting
        run: |
          black --check .
          isort --check .
          mypy agent/

  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run tests
        run: npm test
      - name: Run linting
        run: npm run lint

  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build without SGX feature
        run: cargo build --verbose
      - name: Run tests without SGX feature
        run: cargo test --verbose
      - name: Check code formatting
        run: cargo fmt --all -- --check
      - name: Lint with clippy
        run: cargo clippy -- -D warnings 